version: '3.8'

services:
  app:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/jira?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jira-network

  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jira
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - jira-network

volumes:
  postgres_data:

networks:
  jira-network:
    driver: bridge
